name: test

on: [push, pull_request]

env:
  ENGINE_API_URL: ${{ secrets.ENGINE_API_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  check-magi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: cd magi && cargo check

  test-magi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: cd magi && cargo test --all
